### ISSUE TITLE
Adjust presentation of followup actions box

### ISSUE THREAD

**Issue by msecret** [18F/cg-style#78]
In order to show users a cohesive form experience, form elements should be sized correctly relative to each other and the rest of the UI elements.

**Comment by thisisdano** [comment]
I adjusted this issue to focus on all the elements of what I'm calling the `followup actions box` — the actions needed to complete an parent action, like adding a service instance.

---

In order to for the user to complete an action like adding a service instance, we need to clearly display the needed actions and next steps.

**Acceptance criteria**
- [x] Follow-up actions (FAs) should be clear and distinct from the existing page elements
- [x] FAs should fit in with the existing rhythm of the page
- [x] FAs should be cancel-able
- [x] It should be as clear as possible exactly what FAs are requested
- [x] It should be as clear as possible what parent action the FAs refer to

**Comment by thisisdano** [comment]
This issue is addressed by two PRs:

`cg-style`: https://github.com/18F/cg-style/pull/86
`cg-deck`: https://github.com/18F/cg-deck/pull/338

**Comment by msecret** [comment]
Note: I still have to implement code to make this cancellable
